environment:
  matrix:
  - TOXENV: "py27-pytestlatest"
  - TOXENV: "py34-pytestlatest"
  - TOXENV: "py35-pytestlatest"
  - TOXENV: "py36-pytestlatest"
  - TOXENV: "py37-pytestlatest"
  - TOXENV: "py38-pytestlatest"
  - TOXENV: "py38-pytestmaster"
  - TOXENV: "py38-pytestfeatures"

install:
  - C:\Python38\python -m pip install -U pip setuptools virtualenv
  - C:\Python38\python -m pip install -U tox setuptools_scm

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - C:\Python38\python -m tox

# We don't deploy anything on tags with AppVeyor, we use Travis instead, so we
# might as well save resources
skip_tags: true
