sudo: false
language: python

notifications:
  irc:
    channels:
    - 'chat.freenode.net#pytest'
    on_success: change
    on_failure: change
    skip_join: true
  email:
  - pytest-commit@python.org

python:
- '2.6'
- '2.7'
- '3.4'
- '3.5'
- '3.6'
env:
- TOXENV=py-pytest30
- TOXENV=py-pytest31
- TOXENV=py-pytest32

install: pip install tox setuptools_scm
script: tox

jobs:
  include:
    - stage: test
    # python x env above are already included into this stage
    - python: "3.6"
      env: TOXENV=flakes
    - python: "3.6"
      env: TOXENV=readme

    - stage: deploy
      python: '3.6'
      env:
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: ronny
        skip_upload_docs: true
        password:
          secure: cxmSDho5d+PYKEM4ZCg8ms1P4lzhYkrw6fEOm2HtTcsuCyY6aZMSgImWAnEYbJHSkdzgcxlXK9UKJ9B0YenXmBCkAr7UjdnpNXNmkySr0sYzlH/sfqt/dDATCHFaRKxnkOSOVywaDYhT9n8YudbXI77pXwD12i/CeSSJDbHhsu0JYUfAcb+D6YjRYoA2SEGCnzSzg+gDDfwXZx4ZiODCGLVwieNp1klCg88YROUE1BaYYNuUOONvfXX8+TWowbCF6ChH1WL/bZ49OStEYQNuYxZQZr4yClIqu9VJbchrU8j860K9ott2kkGTgfB/dDrQB/XncBubyIX9ikzCQAmmBXWAI3eyvWLPDk2Jz7kW2l2RT7syct80tCq3JhvQ1qdwr5ap7siocTLgnBW0tF4tkHSTFN3510fkc43npnp6FThebESQpnI24vqpwJ9hI/kW5mYi014Og2E/cpCXnz2XO8iZPDbqAMQpDsqEQoyhfGNgPTGp4K30TxRtwZBI5hHhDKnnR16fXtRgt1gYPvz/peUQvvpOm4JzIzGXPzluuutpnCBy75v5+oiwT3YRrLL/Meims9FtDDXL3qQubAE/ezIOOpm0N5XXV8DxIom8EN71yq5ab1tqhM+tBX7owRjy4FR4If2Q8feBdmTuh26DIQt/y+qSG8VkB9Sw/JCjc7c=
        on:
          tags: true
          distributions: sdist bdist_wheel
          repo: pytest-dev/pytest-xdist
