environment:
  matrix:
  - TOXENV: "py27-pytest36"
  - TOXENV: "py34-pytest36"
  - TOXENV: "py35-pytest36"
  - TOXENV: "py36-pytest36"
  - TOXENV: "py27-pytest36-pexpect"
  - TOXENV: "py36-pytest36-pexpect"

install:
  - C:\Python36\python -m pip install -U tox setuptools_scm pip

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - C:\Python36\python -m tox

# We don't deploy anything on tags with AppVeyor, we use Travis instead, so we
# might as well save resources
skip_tags: true
